# -*- coding: utf-8 -*-
"""plotly_sample

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eFuAhFc40veTHWoAW4uKXgkHt6xeZ5Qe
"""

import plotly.graph_objects as go
import numpy as np

import plotly.express as px
df = px.data.iris()

plot = px.scatter(data_frame=df, x='width', y='y_name', color='species', title='title')


plot.write_html('./index.html',
                full_html=False,
                include_plotlyjs='cdn')







print((str(df.iloc[0,7])))

