# -*- coding: utf-8 -*-
"""plotly_sample

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eFuAhFc40veTHWoAW4uKXgkHt6xeZ5Qe
"""

import plotly.graph_objects as go
import numpy as np

import plotly.express as px
df = px.data.iris()
df
# plot = px.scatter(data_frame=df, x='width', y='y_name', color='species', title='title')
#
#
# plot.write_html('./index.html',
#                 full_html=False,
#                 include_plotlyjs='cdn')




layout = {
  "title": " ",
  "width": 1000,
  "xaxis": {
    "type": "date",
    "range": [1193687871762.1562, 1448946000000],
    "title": " ",
    "showgrid": False,
    "autorange": True,
    "tickformat": ""
  },
  "yaxis": {
    "type": "linear",
    "range": [-100000000, 3600000000],
    "title": " ",
    "autorange": False,
    "gridcolor": "rgb(208, 208, 208)",
    "ticksuffix": "  "
  },
  "height": 350,
  "legend": {
    "x": -0.24796901053454015,
    "y": 0.9713068181818182,
    "bgcolor": "rgba(242, 242, 242, 0)",
    "traceorder": "reversed"
  },
  "margin": {
    "b": 20,
    "l": 175,
    "r": 80,
    "t": 20
  },
  "autosize": False,
  "annotations": [
    {
      "ax": -246,
      "ay": -164,
      "font": {
        "size": 14,
        "color": "rgb(129, 129, 126)"
      },
      "text": "<b>Estimated global install base (bn)</b>",
      "arrowcolor": "rgba(68, 68, 68, 0)"
    }
  ],
  "plot_bgcolor": "rgb(242, 242, 242)",
  "paper_bgcolor": "rgb(242, 242, 242)"
}